repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 21.4b0
    hooks:
    - id: black
      language_version: python3
